FROM node:13.12.0-alpine

# Bundle APP files
COPY index.js .
COPY src src/
COPY package.json .
COPY package-lock.json .
# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install

# start app
CMD ["node", "index"]