version: '3.7'

services:

  wallmartbackend:
    env_file:
      - .env
    container_name: wallmartbackend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true